---
engines:
  duplication:
    enabled: true
    checks:
      Similar code:
        enabled: false
    config:
      languages:
      - php
  fixme:
    enabled: true
  phpmd:
    enabled: true
    config:
      file_extensions:
        - php
      rulesets: "naming,design,codesize"
  phpcodesniffer:
    enabled: true
    config:
      file_extensions: "php,inc,lib"
      standard: "PSR1,PSR2"
      ignore_warnings: true
ratings:
  paths:
  - "**.inc"
  - "**.lib"
  - "**.php"
exclude_paths:
- tests/
- vendor/
- database/
- bootstrap/
